apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: php-nginx
spec:
  selector:
    matchLabels:
      app: php-nginx
  replicas: 3
  strategy:
    type: Recreate
    #type: RollingUpdate
  template:
    metadata:
      labels:
        app: php-nginx
      annotations:
        prometheus.io/port: '80'
        prometheus.io/path: '/metrics/'
        #prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: php-nginx-phpcode
          configMap:
            name: php-nginx-phpcode
      containers:
        - name: php-nginx
          image: 'webdevops/php-nginx:7.4'
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          - mountPath: /app/phpinfo.php
            name: php-nginx-phpcode
            subPath: phpinfo
          - mountPath: /app/metrics/index.php
            name: php-nginx-phpcode
            subPath: phpmetrics
          - mountPath: /app/index.php
            name: php-nginx-phpcode
            subPath: mainindex
