apiVersion: v1
kind: Service
metadata:
  name: php-nginx-service
  namespace: {{ .Values.namespace }}
  labels:
    app: php-nginx
spec:
  type: NodePort
  ports:
  - name: phpnginx
    port: 80
  selector:
      app: php-nginx
